plugins:

  fortinet:
    executor: central_deployment_agent
    package_name: cloudify-fortimanager-plugin
    source: cloudify-fortimanager-plugin
    package_version: '0.0.0.2'

node_types:

  cloudify.fortinet.fortimanager:
    derived_from: cloudify.nodes.Root
    properties:
      host:
        description: >
          Fortimanager hostname or IP addresses
        default: ""
      username:
        description: >
          Fortimanager username
        default: ""
      password:
        description: >
          Fortimanager password
        default: ""
      use_ssl:
        description: >
          http or https
        type: boolean
        default: false
      verify_ssl:
        description: >
          A boolean which controls whether we verify
          the server's TLS certificate.
        type: boolean
        default: true

    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fortinet.fortimanager_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        configure:
          implementation: fortinet.fortimanager_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        start:
          implementation: fortinet.fortimanager_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        stop:
          implementation: fortinet.fortimanager_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''
        delete:
          implementation: fortinet.fortimanager_plugin.tasks.execute
          inputs:
            params:
              default: {}
            template_file:
              default: ''

relationships:
  device_in_fmg:
    derived_from: cloudify.relationships.connected_to
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish:
          implementation: fortinet.fortimanager_plugin.tasks.execute_relation
          inputs:
            template_file:
              default: templates/add-fortigate.yaml
            params:
              default:
                fgt_password: "fortinet"
                fgt_ip: { get_attribute: [TARGET, ip ] }
                fgt_user: "admin"
                fgt_name: { get_attribute: [TARGET, server, name ] }
                fmg_package: { get_input: fmg_package }
        unlink:
          implementation: fortinet.fortimanager_plugin.tasks.execute_relation
          inputs:
            template_file:
              default: templates/remove-fortigate.yaml
            params:
              default:
                fgt_name: { get_attribute: [TARGET, server, name ] }